name: CI/CD Pipeline


# Trigger the workflow on push to the main branch
on:
  push:
    branches: [main]

# Define environment variables
env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 471112745159.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: my-java-app
  CLUSTER_NAME: my-cluster
  IMAGE_TAG: ${{ github.sha }}

# for OIDC
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      # Checkout the source code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client

      # Configure AWS credentials using GitHub Secrets
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::471112745159:role/GitHubActionsOIDCRole
          aws-region: us-east-1
